micronaut:
  application:
    name: backend

micronaut:
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'

micronaut:
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:3000

micronaut:
  http:
    services:
      vat:
        proxy-address: some.proxy.corp.com:8000
        proxy-type: http

datasources:
  default:
    url: jdbc:postgresql://45.10.244.15:55532/work100022
    driverClassName: org.postgresql.Driver
    username: work100022
    password: 'Zf#t*#o~~dSchp9nRj4R'
    dialect: POSTGRES
#    schema-generate: CREATE_DROP

jpa.default.properties.hibernate.hbm2ddl.auto: update

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

netty:
  default:
    allocator:
      max-order: 3
